'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { matchJobs } from '@/lib/jobs'
import {
  ArrowRight,
  ArrowUpRight,
  BriefcaseBusiness,
  Check,
  ChevronDown,
  CirclePlay,
  FileCheck2,
  Filter,
  Gauge,
  Layers3,
  Menu,
  Mic,
  MoveRight,
  Search,
  ShieldCheck,
  Sparkles,
  Target,
  X,
  Zap,
} from 'lucide-react'

const problems = [
  ['01', 'THE ENDLESS SEARCH', 'Hours disappear across LinkedIn, Indeed, company career pages and dozens of job boards.'],
  ['02', 'THE GENERIC RESUME', 'One resume sent everywhere rarely communicates why you are the right candidate.'],
  ['03', 'THE SILENCE', 'Applications disappear into black holes with no clear visibility into what happens next.'],
]

const services = [
  ['AI Job Matching', 'Find roles that fit your skills, ambitions and non-negotiables.', Target],
  ['Resume Optimization', 'Position your experience for the opportunities you actually want.', FileCheck2],
  ['ATS Analysis', 'Know what recruiters and screening systems see before they do.', Gauge],
  ['Application Support', 'Stay organized and intentional from saved to submitted.', Layers3],
  ['Interview Preparation', 'Practice with structure, feedback and confidence.', Mic],
  ['Career Strategy', 'Make your next move with a clear, personal point of view.', Sparkles],
]

const faqs = [
  ['How does Endure Jobs work?', 'We combine intelligent matching, profile optimization and human career support in one focused platform. You define the destination; Endure helps you build the path.'],
  ['How does AI job matching work?', 'Our matching engine considers your skills, experience, target role, location, preferences and growth goals to surface relevant opportunities.'],
  ['Can I upload my existing resume?', 'Yes. Start with the resume you have and use our analyzer to understand what is working and what can be improved.'],
  ['Can I choose which jobs I apply to?', 'Always. Endure Jobs is built around your approval and control. No application is submitted without your say-so.'],
  ['Do humans review my profile?', 'Human-assisted services are transparent and provided with your approval, so technology and expertise work together.'],
]

function Logo() {
  return <a href="#top" className="flex items-center gap-3" aria-label="Endure Jobs home"><img src="/endure-jobs-logo.png" alt="Endure Jobs" className="h-9 w-auto" /><span className="text-[13px] font-bold tracking-[0.18em] text-white">ENDURE <span className="text-cyan-300">JOBS</span></span></a>
}

function SectionLabel({ children }: { children: React.ReactNode }) {
  return <p className="mb-5 text-[10px] font-bold tracking-[0.24em] text-cyan-300">{children}</p>
}

function MatchCard() {
  const [index, setIndex] = useState(0)
  useEffect(() => { const timer = window.setInterval(() => setIndex(i => (i + 1) % matchJobs.length), 5000); return () => window.clearInterval(timer) }, [])
  const job = matchJobs[index]
  return <div className="match-card glass-card animate-float">
    <div className="flex items-center justify-between border-b border-white/10 pb-4"><div><p className="text-[10px] font-bold tracking-[0.18em] text-cyan-300">ENDURE MATCH™ · DEMO</p><p className="mt-2 text-lg font-semibold text-white">{job.title}</p><p className="mt-1 text-xs text-slate-400">{job.company} · {job.location}</p></div><span className="score-ring">{job.matchScore}%</span></div>
    <div className="grid grid-cols-2 gap-4 py-4 text-xs"><div><p className="mb-2 text-slate-500">Skills</p>{job.skills.slice(0,3).map(skill => <p className="text-slate-200" key={skill}>{skill} <Check className="ml-1 inline h-3 w-3 text-cyan-300" /></p>)}</div><div><p className="mb-2 text-slate-500">Details</p><p className="text-slate-200">{job.remoteType}</p><p className="mt-2 text-slate-200">{job.salary}</p></div></div>
    <Link href={`/jobs/${job.id}`} className="flex w-full items-center justify-between rounded-lg bg-white/10 px-4 py-3 text-xs font-semibold text-white transition hover:bg-cyan-300 hover:text-[#07111f]">View job <ArrowUpRight className="h-4 w-4" /></Link><div className="mt-4 flex justify-center gap-2">{matchJobs.map((_, i) => <button aria-label={`Show match ${i + 1}`} key={i} onClick={() => setIndex(i)} className={`h-1.5 w-1.5 rounded-full ${i === index ? 'bg-cyan-300' : 'bg-white/25'}`} />)}</div>
  </div>
}

export default function Page() {
  const [mobileOpen, setMobileOpen] = useState(false)
  const [openFaq, setOpenFaq] = useState(0)
  const [email, setEmail] = useState('')

  return <main id="top" className="min-h-screen overflow-hidden bg-[#07111f] text-white">
    <nav className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#07111f]/75 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 lg:px-10"><Logo /><div className="hidden items-center gap-8 lg:flex"><a href="#platform" className="nav-link">Platform</a><a href="#how-it-works" className="nav-link">How it works</a><a href="#services" className="nav-link">Services</a><a href="#stories" className="nav-link">For candidates</a><a href="#faq" className="nav-link">FAQ</a></div><div className="hidden items-center gap-5 lg:flex"><Link href="/admin/login" className="text-sm font-medium text-slate-300 transition hover:text-white">Admin</Link><Link href="/enroll" className="button-primary px-5 py-3 text-xs">Get started <ArrowRight className="h-4 w-4" /></Link></div><button className="lg:hidden" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Toggle menu">{mobileOpen ? <X /> : <Menu />}</button></div>{mobileOpen && <div className="border-t border-white/10 bg-[#07111f] px-6 py-5 lg:hidden"><div className="flex flex-col gap-5 text-sm"><a href="#platform" onClick={() => setMobileOpen(false)}>Platform</a><a href="#how-it-works" onClick={() => setMobileOpen(false)}>How it works</a><a href="#services" onClick={() => setMobileOpen(false)}>Services</a><a href="#faq" onClick={() => setMobileOpen(false)}>FAQ</a><button className="button-primary justify-center">Get started <ArrowRight className="h-4 w-4" /></button></div></div>}</nav>

    <section className="hero relative flex min-h-screen items-center"><video className="absolute inset-0 h-full w-full object-cover opacity-40" autoPlay muted loop playsInline preload="auto" onEnded={(event) => { event.currentTarget.currentTime = 0; void event.currentTarget.play() }} poster="https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=2200&q=80"><source src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/5442621-uhd_3840_2160_25fps-aR8drBMt9pCcYn3TfOubYfmtdfNnvd.mp4" type="video/mp4" /></video><div className="hero-overlay absolute inset-0" /><div className="hero-grid absolute inset-0 opacity-30" /><div className="relative z-10 mx-auto grid w-full max-w-7xl items-center gap-16 px-6 pb-16 pt-32 lg:grid-cols-[1fr_390px] lg:px-10"><div className="max-w-3xl"><SectionLabel>CAREERS DON&apos;T HAPPEN BY ACCIDENT.</SectionLabel><h1 className="text-balance text-5xl font-semibold leading-[0.98] tracking-[-0.055em] sm:text-7xl lg:text-[92px]">Endure the search.<br /><span className="text-cyan-300">Earn the opportunity.</span></h1><p className="mt-8 max-w-xl text-base leading-7 text-slate-300 sm:text-lg">Endure Jobs combines intelligent matching, career strategy, resume optimization, application support and interview preparation to help you move from searching to hired.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/enroll" className="button-primary">Get started <ArrowRight className="h-4 w-4" /></Link><a href="#how-it-works" className="button-secondary">See how it works <MoveRight className="h-4 w-4" /></a></div><div className="mt-12 flex flex-wrap gap-7 text-[10px] font-bold tracking-[0.18em] text-slate-400"><span><span className="mr-2 text-cyan-300">*</span>SEARCH</span><span><span className="mr-2 text-cyan-300">*</span>PROCESS</span><span><span className="mr-2 text-cyan-300">*</span>HIRED</span></div></div><MatchCard /></div><div className="absolute bottom-8 left-1/2 z-10 hidden -translate-x-1/2 items-center gap-3 text-[9px] tracking-[0.25em] text-slate-400 sm:flex"><span className="scroll-line" /> SCROLL TO EXPLORE</div></section>

    <section className="border-y border-white/10 bg-[#0a1728] py-9"><div className="mx-auto grid max-w-7xl gap-8 px-6 sm:grid-cols-2 lg:grid-cols-4 lg:px-10"><div className="sm:col-span-2 lg:col-span-1"><p className="text-sm font-semibold leading-6 text-white">Built for people who refuse to stop.</p><p className="mt-2 text-xs text-slate-500">Your next move starts with momentum.</p></div>{[['10,000+', 'Candidate profiles'], ['25,000+', 'Job matches'], ['50,000+', 'Applications supported']].map(([num, label]) => <div key={label} className="border-l border-white/10 pl-5"><p className="text-3xl font-semibold tracking-tight text-cyan-300">{num}</p><p className="mt-1 text-xs text-slate-400">{label}</p></div>)}</div></section>

    <section className="section-padding bg-[#07111f]"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="max-w-2xl"><SectionLabel>THE OLD WAY IS BROKEN</SectionLabel><h2 className="display-heading">The job search shouldn&apos;t feel like a second job.</h2></div><div className="mt-16 grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 md:grid-cols-3">{problems.map(([num, title, copy]) => <article key={num} className="problem-card bg-[#0b1728] p-8 md:p-10"><span className="text-xs font-semibold text-cyan-300">{num}</span><div className="mt-24"><h3 className="text-sm font-semibold tracking-[0.15em] text-white">{title}</h3><p className="mt-4 text-sm leading-6 text-slate-400">{copy}</p></div><ArrowUpRight className="mt-10 h-5 w-5 text-slate-600 transition group-hover:text-cyan-300" /></article>)}</div></div></section>

    <section id="how-it-works" className="section-padding bg-[#f4f7fb] text-[#07111f]"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="grid gap-14 lg:grid-cols-[0.8fr_1.2fr] lg:items-end"><div><SectionLabel>THE ENDURE ENGINE</SectionLabel><h2 className="display-heading text-[#07111f]">One career engine. Everything you need to move forward.</h2></div><p className="max-w-md text-base leading-7 text-slate-500">Technology finds the opportunity. AI improves your positioning. Humans provide strategy. You stay in control of the journey.</p></div><div className="mt-20 grid grid-cols-2 gap-0 border-y border-slate-200 sm:grid-cols-3 lg:grid-cols-6">{['Profile', 'Match', 'Optimize', 'Apply', 'Interview', 'Get hired'].map((item, i) => <div key={item} className="workflow-step group border-r border-slate-200 py-8 last:border-0"><span className="text-xs font-bold text-cyan-600">0{i + 1}</span><p className="mt-8 text-sm font-semibold">{item}</p><span className="mt-5 block h-px w-10 bg-cyan-500 transition-all group-hover:w-20" /></div>)}</div></div></section>

    <section id="platform" className="section-padding bg-[#0b1728]"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="grid gap-14 lg:grid-cols-[0.7fr_1.3fr] lg:items-center"><div><SectionLabel>AI JOB MATCHING</SectionLabel><h2 className="display-heading">Stop chasing jobs. Start finding the right ones.</h2><p className="mt-7 max-w-md leading-7 text-slate-400">Endure analyzes the signal behind your experience and preferences, so the roles you see feel considered, relevant and worth your time.</p><button className="button-primary mt-9">Explore matching <ArrowRight className="h-4 w-4" /></button></div><div className="product-panel"><div className="flex items-center justify-between border-b border-slate-200 pb-5"><div><p className="text-[10px] font-bold tracking-[0.18em] text-cyan-600">AI MATCH</p><p className="mt-2 text-2xl font-semibold">Software Engineer</p><p className="mt-1 text-sm text-slate-500">New York · Hybrid</p></div><div className="text-right"><p className="text-4xl font-semibold text-cyan-600">92%</p><p className="text-[10px] font-bold tracking-widest text-slate-400">MATCH SCORE</p></div></div><div className="grid gap-5 py-7 sm:grid-cols-2">{[['Skill match', '95%'], ['Experience match', '90%'], ['Role match', '94%'], ['Location match', '88%']].map(([label, value]) => <div key={label}><div className="mb-2 flex justify-between text-xs"><span className="text-slate-500">{label}</span><span className="font-semibold">{value}</span></div><div className="h-1.5 rounded-full bg-slate-200"><div className="h-full rounded-full bg-cyan-500" style={{ width: value }} /></div></div>)}</div><div className="flex flex-wrap gap-2 border-t border-slate-200 pt-5">{['Remote', '$110k+', '5+ years', 'Fintech'].map(filter => <span key={filter} className="rounded-full bg-slate-100 px-3 py-1.5 text-[11px] text-slate-600"><Filter className="mr-1 inline h-3 w-3" />{filter}</span>)}</div></div></div></div></section>

    <section className="section-padding bg-[#07111f]"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="grid gap-14 lg:grid-cols-2 lg:items-center"><div className="resume-panel order-2 lg:order-1"><div className="mb-5 flex items-center justify-between"><span className="text-[10px] font-bold tracking-widest text-slate-500">MASTER RESUME</span><span className="rounded-full bg-cyan-300/10 px-3 py-1 text-[10px] text-cyan-300">LIVE ANALYSIS</span></div><div className="rounded-xl border border-white/10 bg-white/[0.04] p-5"><div className="h-2 w-2/5 rounded bg-white/30" /><div className="mt-4 h-2 w-4/5 rounded bg-white/10" /><div className="mt-2 h-2 w-3/5 rounded bg-cyan-300/50" /><div className="mt-8 grid grid-cols-3 gap-2"><div className="h-14 rounded bg-white/5" /><div className="h-14 rounded bg-cyan-300/20" /><div className="h-14 rounded bg-white/5" /></div><div className="mt-6 h-2 w-full rounded bg-white/10" /><div className="mt-2 h-2 w-5/6 rounded bg-white/10" /></div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><div><p className="text-xl font-semibold text-cyan-300">94%</p><p className="text-[9px] text-slate-500">ATS compatible</p></div><div><p className="text-xl font-semibold text-cyan-300">91%</p><p className="text-[9px] text-slate-500">Keyword match</p></div><div><p className="text-xl font-semibold text-cyan-300">96%</p><p className="text-[9px] text-slate-500">Role alignment</p></div></div></div><div className="order-1 lg:order-2"><SectionLabel>AI RESUME ENGINE</SectionLabel><h2 className="display-heading">One profile. A resume built for every opportunity.</h2><p className="mt-7 max-w-md leading-7 text-slate-400">Turn your experience into a sharper, more relevant story for every role without losing the thread of who you are.</p><button className="button-secondary mt-9">Optimize my resume <ArrowRight className="h-4 w-4" /></button></div></div></div></section>

    <section className="section-padding bg-[#f4f7fb] text-[#07111f]"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="grid gap-10 lg:grid-cols-[1fr_1.1fr] lg:items-center"><div><SectionLabel>APPLICATION CONTROL</SectionLabel><h2 className="display-heading text-[#07111f]">Applications without the chaos.</h2><p className="mt-6 max-w-md leading-7 text-slate-500">A simple, visual system for every opportunity — from your first save to the offer you accept.</p></div><div className="kanban-wrap"><div className="kanban-grid">{[['Saved', '2'], ['Applied', '4'], ['Interview', '2']].map(([label, count], i) => <div key={label} className="kanban-col"><div className="mb-4 flex items-center justify-between text-[10px] font-bold uppercase tracking-widest text-slate-400"><span>{label}</span><span>{count}</span></div><div className="mb-3 rounded-lg border border-slate-200 bg-white p-3 shadow-sm"><div className="flex items-start justify-between"><span className="h-6 w-6 rounded bg-slate-100" /><span className="text-[10px] font-bold text-cyan-600">92%</span></div><p className="mt-3 text-xs font-semibold">Software Engineer</p><p className="mt-1 text-[10px] text-slate-400">Vertex Labs</p></div></div>)}</div></div></div></div></section>

    <section id="services" className="section-padding bg-[#07111f]"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><SectionLabel>THE FULL STACK FOR YOUR NEXT MOVE</SectionLabel><h2 className="display-heading">A career advantage, built around you.</h2></div><a href="#contact" className="text-sm font-semibold text-cyan-300">View all services <ArrowRight className="ml-2 inline h-4 w-4" /></a></div><div className="mt-14 grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-3">{services.map(([title, copy, Icon]) => <div key={title as string} className="group bg-[#0b1728] p-7 transition hover:bg-[#10233a]"><Icon className="h-5 w-5 text-cyan-300" /><h3 className="mt-12 text-sm font-semibold">{title as string}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{copy as string}</p><ArrowUpRight className="mt-8 h-4 w-4 text-slate-600 transition group-hover:text-cyan-300" /></div>)}</div></div></section>

    <section id="stories" className="section-padding bg-[#0b1728]"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="grid gap-12 lg:grid-cols-[1fr_1.1fr] lg:items-center"><div><SectionLabel>TECHNOLOGY + PEOPLE</SectionLabel><h2 className="display-heading">Technology finds the opportunity. People help you win it.</h2><p className="mt-7 max-w-md leading-7 text-slate-400">A career strategist, resume specialist and interview coach — brought in when you need more than an algorithm.</p><div className="mt-9 space-y-5">{[['Career strategist', 'Define target roles and career direction.'], ['Resume specialist', 'Sharpen your professional positioning.'], ['Interview coach', 'Prepare for the moments that matter.']].map(([title, copy], i) => <div key={title} className="flex gap-4 border-t border-white/10 pt-5"><span className="text-xs text-cyan-300">0{i + 1}</span><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-sm text-slate-400">{copy}</p></div></div>)}</div></div><div className="relative overflow-hidden rounded-2xl"><img src="https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=85" alt="Professionals collaborating around a table" className="h-[520px] w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#07111f] via-transparent to-transparent" /><div className="absolute bottom-7 left-7"><p className="text-2xl font-semibold">Your ambition, <span className="text-cyan-300">amplified.</span></p></div></div></div></div></section>

    <section id="faq" className="section-padding bg-[#f4f7fb] text-[#07111f]"><div className="mx-auto max-w-4xl px-6 lg:px-10"><div className="text-center"><SectionLabel>QUESTIONS, ANSWERED</SectionLabel><h2 className="display-heading text-[#07111f]">Start with clarity.</h2></div><div className="mt-14 border-t border-slate-200">{faqs.map(([question, answer], i) => <div key={question} className="border-b border-slate-200"><button className="flex w-full items-center justify-between py-6 text-left text-sm font-semibold" onClick={() => setOpenFaq(openFaq === i ? -1 : i)}><span>{question}</span><ChevronDown className={`h-4 w-4 text-cyan-600 transition ${openFaq === i ? 'rotate-180' : ''}`} /></button>{openFaq === i && <p className="max-w-2xl pb-6 text-sm leading-6 text-slate-500">{answer}</p>}</div>)}</div></div></section>

    <section id="contact" className="cta-section relative overflow-hidden"><div className="hero-grid absolute inset-0 opacity-30" /><div className="relative mx-auto max-w-5xl px-6 py-28 text-center lg:py-36"><SectionLabel>THE NEXT CHAPTER STARTS HERE</SectionLabel><h2 className="mx-auto max-w-4xl text-balance text-5xl font-semibold tracking-[-0.05em] sm:text-7xl">Your next opportunity <span className="text-cyan-300">starts here.</span></h2><p className="mx-auto mt-7 max-w-xl text-slate-300">Some people stop when the applications stop getting responses. Endure Jobs exists for the people who keep going.</p><div className="mt-10 flex flex-col justify-center gap-3 sm:flex-row"><button className="button-primary">Start your journey <ArrowRight className="h-4 w-4" /></button><button className="button-secondary">Talk to an expert <ArrowRight className="h-4 w-4" /></button></div></div></section>

    <footer className="border-t border-white/10 bg-[#07111f]"><div className="mx-auto max-w-7xl px-6 py-16 lg:px-10"><div className="grid gap-12 lg:grid-cols-[1.3fr_2fr_1.2fr]"><div><Logo /><p className="mt-5 max-w-xs text-sm leading-6 text-slate-500">Your career. Our commitment.</p><div className="mt-8 flex gap-3"><a className="social-icon" href="#" aria-label="LinkedIn"><BriefcaseBusiness className="h-4 w-4" /></a><a className="social-icon" href="#" aria-label="Search"><Search className="h-4 w-4" /></a></div></div><div className="grid grid-cols-2 gap-8 sm:grid-cols-3"><div><p className="footer-heading">Platform</p><div className="footer-links"><a href="#platform">Job matching</a><a href="#platform">Resume engine</a><a href="#services">Application tracker</a><a href="#services">Interview prep</a></div></div><div><p className="footer-heading">Company</p><div className="footer-links"><a href="#stories">About</a><a href="#contact">Contact</a><a href="#faq">FAQ</a><a href="#contact">Careers</a></div></div><div><p className="footer-heading">Resources</p><div className="footer-links"><a href="#">Career guides</a><a href="#">Resume guides</a><a href="#">Interview tips</a><a href="#">Job search</a></div></div></div><div><p className="footer-heading">Get smarter career insights.</p><p className="mt-3 text-sm leading-6 text-slate-500">One useful note for your next move, occasionally.</p><div className="mt-5 flex border-b border-white/20 pb-3"><input value={email} onChange={e => setEmail(e.target.value)} type="email" placeholder="Your email address" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-slate-600" aria-label="Email address" /><button aria-label="Subscribe" className="text-cyan-300"><ArrowRight className="h-4 w-4" /></button></div></div></div><div className="mt-16 flex flex-col justify-between gap-4 border-t border-white/10 pt-6 text-[10px] text-slate-600 sm:flex-row"><p>© 2026 Endure Jobs. All rights reserved.</p><div className="flex gap-5"><a href="#">Privacy</a><a href="#">Terms</a><a href="#">Cookies</a></div></div></div></footer>
  </main>
}
